name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes automatizados
        run: npm test

  lighthouse:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Iniciar servidor local
        run: npx http-server -p 8080 &

      - name: Rodar Lighthouse
        run: npm run lighthouse

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload de artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
